"""

Revision ID: 0a4f4d163349
Revises: 459453dd3c9f
Create Date: 2025-07-14 22:08:31.092070

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0a4f4d163349"
down_revision: Union[str, Sequence[str], None] = "459453dd3c9f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "games", "game_img", existing_type=sa.VARCHAR(length=255), nullable=True
    )
    op.add_column("matches", sa.Column("created_by_id", sa.UUID(), nullable=True))
    op.add_column(
        "matches",
        sa.Column(
            "base_bet_amount",
            sa.Float(),
            nullable=True,
            comment="Monto base apostado en la partida",
        ),
    )
    op.create_foreign_key(
        None, "matches", "users", ["created_by_id"], ["user_id"], ondelete="SET NULL"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "matches", type_="foreignkey")
    op.drop_column("matches", "base_bet_amount")
    op.drop_column("matches", "created_by_id")
    op.alter_column(
        "games", "game_img", existing_type=sa.VARCHAR(length=255), nullable=False
    )
    # ### end Alembic commands ###
