""" 

Revision ID: 0e3d9acb859b
Revises: 1ffeb1d7e375
Create Date: 2025-07-16 09:29:11.233542

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e3d9acb859b'
down_revision: Union[str, Sequence[str], None] = '1ffeb1d7e375'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("UPDATE games SET house_odds = 1.0 WHERE house_odds IS NULL")

    # Paso 2: Marcar la columna como NOT NULL
    op.alter_column('games', 'house_odds',
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        nullable=False
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('games', 'house_odds')
    # ### end Alembic commands ###
