"""

Revision ID: 0e4218ec8dec
Revises: 93b9c478a068
Create Date: 2025-07-15 00:22:53.534054

"""
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "0e4218ec8dec"
down_revision: Union[str, Sequence[str], None] = "93b9c478a068"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
