"""

Revision ID: 11239fa7e45b
Revises: caac04cf31ac
Create Date: 2025-07-15 00:17:11.018174

"""
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "11239fa7e45b"
down_revision: Union[str, Sequence[str], None] = "caac04cf31ac"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
