"""

Revision ID: 1ffeb1d7e375
Revises: 0e4218ec8dec
Create Date: 2025-07-15 15:51:57.821252

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1ffeb1d7e375"
down_revision: Union[str, Sequence[str], None] = "0e4218ec8dec"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "games",
        sa.Column("game_capacity", sa.Integer(), nullable=False, server_default="1"),
    )
    op.create_index(
        op.f("ix_games_game_capacity"), "games", ["game_capacity"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_games_game_capacity"), table_name="games")
    op.drop_column("games", "game_capacity")
    # ### end Alembic commands ###
