"""

Revision ID: 959df354bc30
Revises: a52ad37a832e
Create Date: 2025-07-15 00:14:24.257432

"""
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "959df354bc30"
down_revision: Union[str, Sequence[str], None] = "a52ad37a832e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
