"""

Revision ID: 9aed75ff9bbc
Revises: 0e3d9acb859b
Create Date: 2025-07-16 09:32:54.642802

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9aed75ff9bbc"
down_revision: Union[str, Sequence[str], None] = "0e3d9acb859b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("UPDATE games SET house_odds = 1.0 WHERE house_odds IS NULL")

    # Paso 2: Marcar la columna como NOT NULL
    op.alter_column(
        "games",
        "house_odds",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        nullable=False,
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "games",
        "house_odds",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        nullable=True,
    )
    # ### end Alembic commands ###
