""" 

Revision ID: a52ad37a832e
Revises: 0a4f4d163349
Create Date: 2025-07-14 23:17:44.268797

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a52ad37a832e'
down_revision: Union[str, Sequence[str], None] = '0a4f4d163349'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('matches', 'game_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_column('matches', 'start_time')
    op.drop_column('matches', 'end_time')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matches', sa.Column('end_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.add_column('matches', sa.Column('start_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.alter_column('matches', 'game_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
