"""Fix after model imports

Revision ID: cae122606537
Revises:
Create Date: 2025-07-26 17:04:08.664042

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "cae122606537"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "matches",
        sa.Column(
            "is_finished",
            sa.Boolean(),
            nullable=True,
            comment="Indica si la partida ha finalizado",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("matches", "is_finished")
    # ### end Alembic commands ###
