"""

Revision ID: d2c201291b3a
Revises: db1ecf99e108
Create Date: 2025-07-29 21:26:42.200960

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d2c201291b3a"
down_revision: Union[str, Sequence[str], None] = "db1ecf99e108"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "app_info",
        "site_icon",
        existing_type=sa.VARCHAR(length=100),
        type_=sa.String(length=250),
        existing_nullable=False,
    )
    op.alter_column(
        "app_info",
        "site_logo",
        existing_type=sa.VARCHAR(length=100),
        type_=sa.String(length=250),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "app_info",
        "site_logo",
        existing_type=sa.String(length=250),
        type_=sa.VARCHAR(length=100),
        existing_nullable=False,
    )
    op.alter_column(
        "app_info",
        "site_icon",
        existing_type=sa.String(length=250),
        type_=sa.VARCHAR(length=100),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
