"""

Revision ID: d565880b678c
Revises: cae122606537
Create Date: 2025-07-28 22:17:23.824142

"""
from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "d565880b678c"
down_revision: Union[str, Sequence[str], None] = "cae122606537"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
