"""

Revision ID: db1ecf99e108
Revises: ea471a1563fd
Create Date: 2025-07-28 22:30:50.632716

"""
from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "db1ecf99e108"
down_revision: Union[str, Sequence[str], None] = "ea471a1563fd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("ALTER TYPE gametype ADD VALUE 'LUCK'")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
