"""

Revision ID: ea471a1563fd
Revises: d565880b678c
Create Date: 2025-07-28 22:29:14.748472

"""
from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "ea471a1563fd"
down_revision: Union[str, Sequence[str], None] = "d565880b678c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
